[MFLOG|0|2022-12-05T21:54:05.569286Z|runtime|26dece33-07a2-49ae-a866-2b371fd75865]<flow MyClassificationFlow step load_pos_neg_words> failed:
[MFLOG|0|2022-12-05T21:54:05.573331Z|runtime|9157c1d2-8e0c-4364-aa50-6491f9f35c10]    Internal error
[MFLOG|0|2022-12-05T21:54:05.573999Z|runtime|a5d1add4-8869-4099-809f-b07336fa9272]Traceback (most recent call last):
[MFLOG|0|2022-12-05T21:54:05.574072Z|runtime|de89dd41-bc85-4907-9436-510887dfa36f]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/cli.py", line 1171, in main
[MFLOG|0|2022-12-05T21:54:05.574135Z|runtime|743750a0-ef55-4ee8-aa03-c27d4cfd03e1]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2022-12-05T21:54:05.574199Z|runtime|6cc62d1d-5c33-4974-8f5c-5de6d82a7a49]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2022-12-05T21:54:05.574250Z|runtime|c45c6f73-a19f-48dc-b7c5-dd55fdfcbafa]    return self.main(args, kwargs)
[MFLOG|0|2022-12-05T21:54:05.859262Z|runtime|843b3838-1433-4365-9293-2e2f53b77a2e]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2022-12-05T21:54:05.859503Z|runtime|e2d7e52e-cac6-4374-9cb8-132dcabb4768]    rv = self.invoke(ctx)
[MFLOG|0|2022-12-05T21:54:05.859569Z|runtime|dd832b43-c159-4c68-80d0-a78096443d39]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2022-12-05T21:54:05.859614Z|runtime|abbde20e-5135-4086-aaaa-4792d57c01d2]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2022-12-05T21:54:05.859655Z|runtime|4cc06568-f998-4813-82f9-bc768d670f01]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2022-12-05T21:54:05.859695Z|runtime|d14b8b10-d177-4693-a28c-bb24a67e279c]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2022-12-05T21:54:05.859733Z|runtime|2cff7673-d7ba-43cc-94f6-16bc2156a47f]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2022-12-05T21:54:05.859772Z|runtime|253f3174-a4b6-4079-822c-60b9abfd0875]    return callback(args, kwargs)
[MFLOG|0|2022-12-05T21:54:05.859810Z|runtime|874505e1-f67c-4183-98e3-1126e90a78e9]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2022-12-05T21:54:05.859851Z|runtime|c4643dd6-a07c-4a2d-b516-6f200ffec27a]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2022-12-05T21:54:05.859890Z|runtime|9cce0d5f-82ab-48f0-95c3-b906380b8b9c]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/cli.py", line 580, in step
[MFLOG|0|2022-12-05T21:54:05.859931Z|runtime|6e104a0e-977b-4c8b-ac62-ceb1a6f66916]    task.run_step(
[MFLOG|0|2022-12-05T21:54:05.859969Z|runtime|5fa21683-17dd-4c22-aed0-0f11dbbaf712]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/task.py", line 587, in run_step
[MFLOG|0|2022-12-05T21:54:05.860008Z|runtime|6363f2b7-b69b-48a8-8350-d00a8ef3659c]    self._exec_step_function(step_func)
[MFLOG|0|2022-12-05T21:54:05.860048Z|runtime|7a074c66-d867-4a80-8dcc-24caee874a00]  File "/Users/lyric/opt/anaconda3/envs/mlsys/lib/python3.9/site-packages/metaflow/task.py", line 61, in _exec_step_function
[MFLOG|0|2022-12-05T21:54:05.860089Z|runtime|b2511680-80ec-4aa1-a974-695d1c92961a]    step_function()
[MFLOG|0|2022-12-05T21:54:05.860129Z|runtime|eda8542e-c959-4487-aa72-e35f17833a55]  File "/Users/lyric/Dropbox/Code/MLSys-Final/tmp/final.py", line 295, in load_pos_neg_words
[MFLOG|0|2022-12-05T21:54:05.860231Z|runtime|ec48ea0f-d8dc-47ad-9f9e-76059e96e4ca]    with open('/Users/houdeliao/Desktop/negative.txt','r') as n:
[MFLOG|0|2022-12-05T21:54:05.860287Z|runtime|4805b44c-3e84-49b2-804d-0ec85349a1ce]FileNotFoundError: [Errno 2] No such file or directory: '/Users/houdeliao/Desktop/negative.txt'
[MFLOG|0|2022-12-05T21:54:05.860342Z|runtime|7ecb0f7c-b9cb-4a0f-a30b-9108d09605c9]
[MFLOG|0|2022-12-05T21:54:05.862754Z|runtime|e174a26d-c783-45f4-a9bb-a14aa33b7f11]Task failed.